fails:Kernel.catch yields a new, unique object when called without arguments
